spring:
  application:
    name: oauth-server
  mvc:
    view:
      prefix: /
      suffix: .html
  session:
    store-type: redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  main:
    allow-bean-definition-overriding: true # 但遇到相同名字的时候，是否允许覆盖注册
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 300
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0


server:
  port: 8081
  servlet:
    session:
      timeout: 3600

#mybatis:
#  mapper-locations: classpath*:mybatis/xml/*.xml
#  type-aliases-package: com.yungyu.oauthserver.entity

mybatis-plus:
    mapper-locations: classpath*:mybatis/xml/*.xml
    type-aliases-package: com.yungyu.oauthserver.entity

logging:
  level:
    com:
      yungyu:
        oauthserver:
          mapper: debug