spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcoulddemo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  security:
#    user:
#      name: "admin"
#      password: "666"
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-location: classpath*:mapper/xml/*.xml
  typeAliasesPackage: com.yungyu.oauthserver.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt配置
#jwt:
#  secret: mySecret
#  # 有效时间
#  header: Authorization
#  expiration: 604800
#  tokenHead: Bearer