server:
  port: 8091
spring:
  application:
    name: bpm-demo
    activiti:
      enableSchemaUpdate: true
      databaseType: mysql
      fontName: 正楷
      annotationFontName: 正楷
      labelFontName: 正楷
      enableRunAllTasks: false
  #process-definition-location-suffixes: #流程文件格式
  #  - **.bpmn20.xml
  #  - **.bpmn
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcoulddemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20